
- name: Setup
  hosts: node0
  sudo: yes

  vars:
   - home_dir: /home/vagrant
   - app_dir: App
   - temp_dir: /tmp/

  tasks:
   - name: Install Packages
     apt: name={{ item }} update_cache=yes state=latest
     with_items:
       - build-essential
       - npm
       - nodejs-legacy
       - git

   - name: Install forever
     npm: name={{ item }} global=yes state=present
     with_items:
       - forever

   - name: Clone git repo
     git:
      repo: https://github.com/CSC-DevOps/App.git
      dest: "{{home_dir}}/{{app_dir}}"
     register: git_cloned

   - name: Install npm packages
     npm:
      path: "{{home_dir}}/{{app_dir}}"
