- name: Tasks
  hosts: node0
  vars:
    dest_dir : /home/vagrant/github/App

  tasks:
  - name: Run app forever
    command: forever start "{{ dest_dir }}/main.js" 8000
  - name: Install bash, openssl, openssh-client, and openssh-server
    sudo: yes
    apt: name={{item}} state=latest
    with_items:
       - bash
       - openssl
       - openssh-client
       - openssh-server

  - name: Delete everything in /tmp/*
    sudo: yes
    file:
      path : /tmp/
      state : absent

  - name: Recreate /tmp
    sudo: yes
    file:
      path : /tmp/
      state : directory
