- name: Tasks
  hosts: node0
  sudo: yes

  vars:
   - home_dir: /home/vagrant
   - app_dir: App
   - temp_dir: /tmp/

  tasks:
   - name: Run webserver
     command: forever start "{{home_dir}}/{{app_dir}}/main.js" 8000

   - name: Security
     apt: name={{ item }} state=latest
     with_items:
      - bash
      - openssl
      - openssh-client
      - openssh-server

   - shell: ls -1 "{{temp_dir}}"
     register: contents

   - name: Cleanup
     file:
      path: "{{ temp_dir }}{{ item }}"
      state: absent
     with_items:
       - "{{ contents.stdout_lines}}"






